In [4]:
import numpy as np
print(np.__version__)

arr = numpy.array([1, 2, 3, 4, 5])

print(arr)
print(type(arr))

1.22.4
[1 2 3 4 5]
<class 'numpy.ndarray'>


In [15]:
arr = np.array(42)  #0d array

print("\n",arr)

arr = numpy.array([1, 2, 3, 4, 5]) #1d array

print("\n",arr)

arr = np.array([[1, 2, 3], [4, 5, 6]])   #2d array

print("\n",arr)

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])     #3d array

print("\n",arr)


 42

 [1 2 3 4 5]

 [[1 2 3]
 [4 5 6]]

 [[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [17]:
a = np.array(42)  #Check Number of Dimensions
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [18]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [24]:
arr = np.array([1, 2, 3, 4])   #Access Array Elements

print("\n",arr[0])
print("\n",arr[1])
print("\n",arr[2] + arr[3])


 1

 2

 7


In [21]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])   #Access Array Elements

print('2nd element on 1st row: \n', arr[0, 1])

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('5th element on 2nd row: \n', arr[1, 4])

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: \n', arr[1, -1])

2nd element on 1st row: 
 2
5th element on 2nd row: 
 10
6
Last element from 2nd dim:  10


In [22]:
#slicing
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])
print(arr[4:])
print(arr[:4])
print(arr[-3:-1])
print(arr[1:5:2])
print(arr[::2])

[2 3 4 5]
[5 6 7]
[1 2 3 4]
[5 6]
[2 4]
[1 3 5 7]


In [23]:
#2d_slicing
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print("\n",arr[0:2, 2])
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print("\n",arr[0:2, 1:4])

[7 8 9]

 [3 8]

 [[2 3 4]
 [7 8 9]]


In [28]:
#data_type
arr = np.array(['apple', 'banana', 'cherry'])

print("\n",arr.dtype)
arr = np.array([1, 2, 3, 4], dtype='S')

print("\n",arr)
print("\n",arr.dtype)

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print("\n",newarr)
print("\n",newarr.dtype)


 <U6

 [b'1' b'2' b'3' b'4']

 |S1

 [1 2 3]

 int32


In [29]:
arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


In [30]:
#Copy_&_view
#copy
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

#view
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

#change in view
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)
#if Array Owns its Data
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)



[42  2  3  4  5]
[1 2 3 4 5]
[42  2  3  4  5]
[42  2  3  4  5]
[31  2  3  4  5]
[31  2  3  4  5]
None
[1 2 3 4 5]


In [31]:
#shape
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

#reshape
#1d to 2d

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)
#1d to 3d
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

(2, 4)
[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [32]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4).base)

[1 2 3 4 5 6 7 8]


In [33]:
#Flattening

arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


In [34]:
#Iterating 2-D Arrays
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


In [35]:
#Iterating 3-D Arrays
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [36]:
#Iterating Array With Different Data Types

arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

b'1'
b'2'
b'3'


In [37]:
#NumPy Joining Array
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

#Join two 2-D array
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)
#Stacking Along Rows
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[1 2 3 4 5 6]
[[1 2 5 6]
 [3 4 7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [40]:
#splitting
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print("\n",newarr)
#Access the splitted arrays:

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print("\n",newarr[0])
print("\n",newarr[1])
print("\n",newarr[2])

#Splitting 2-D Arrays

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print("\n",newarr)
#Split the 2-D array into three 2-D
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print("\n",newarr)
#Use the hsplit() method

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print("\n",newarr)


 [array([1, 2]), array([3, 4]), array([5, 6])]

 [1 2]

 [3 4]

 [5 6]

 [array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]

 [array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]

 [array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]
