<a href="https://colab.research.google.com/github/MuhtasimMahadi/Big_data_and_iot_lab/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

In [ ]:
data=[[1,2],[3,4]]
x_data= torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [ ]:
arr=np.array(data)
arr

array([[1, 2],
       [3, 4]])

In [ ]:
x=torch.from_numpy(arr)
x

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [ ]:
x_ones= torch.ones_like(x)
x_ones

tensor([[1, 1],
        [1, 1]], dtype=torch.int32)

In [ ]:
x_zeros= torch.zeros_like(x)
x_zeros

tensor([[0, 0],
        [0, 0]], dtype=torch.int32)

In [ ]:
x_rand= torch.rand_like(x, dtype=torch.float)
x_rand

tensor([[0.3538, 0.6149],
        [0.8535, 0.5190]])

In [ ]:
rand_tensor= torch.rand(2,3)
rand_tensor

tensor([[0.0137, 0.1747, 0.1486],
        [0.1581, 0.8486, 0.2128]])

In [ ]:
ones_tensor= torch.ones(2,3, dtype=torch.float32)
ones_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
zeros_tensor= torch.zeros(2,3)
zeros_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
rand_tensor.shape

torch.Size([2, 3])

In [ ]:
rand_tensor.dtype

torch.float32

In [ ]:
rand_tensor.device

device(type='cpu')

In [ ]:
if torch.cuda.is_available():
    rand_tensor = rand_tensor.to('cuda')

In [ ]:
 rand_tensor

tensor([[0.0137, 0.1747, 0.1486],
        [0.1581, 0.8486, 0.2128]])

In [ ]:
rand_tensor[:,1]=1
rand_tensor

tensor([[0.0137, 1.0000, 0.1486],
        [0.1581, 1.0000, 0.2128]])

In [ ]:
rand_tensor[0]

tensor([0.0137, 1.0000, 0.1486])

In [ ]:
rand_tensor[:,0]

tensor([0.0137, 0.1581])

In [ ]:
rand_tensor[...,-1]

tensor([0.1486, 0.2128])

In [ ]:
rand_tensor.sum()

tensor(2.5332)

In [ ]:
rand_tensor.sum().item()

2.533215284347534

In [ ]:
t1= torch.cat([rand_tensor, zeros_tensor],dim=1)
t1

tensor([[0.0137, 1.0000, 0.1486, 0.0000, 0.0000, 0.0000],
        [0.1581, 1.0000, 0.2128, 0.0000, 0.0000, 0.0000]])

In [ ]:
t2= torch.cat([rand_tensor, zeros_tensor],dim=0)
t2

tensor([[0.0137, 1.0000, 0.1486],
        [0.1581, 1.0000, 0.2128],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000]])

In [ ]:
rand_tensor.mul(ones_tensor)

tensor([[0.0137, 1.0000, 0.1486],
        [0.1581, 1.0000, 0.2128]])

In [ ]:
rand_tensor.matmul(rand_tensor.T)

tensor([[1.0223, 1.0338],
        [1.0338, 1.0703]])

In [ ]:
rand_tensor.add_(5)

tensor([[5.0137, 6.0000, 5.1486],
        [5.1581, 6.0000, 5.2128]])

In [ ]:
n= np.ones(5)
n

array([1., 1., 1., 1., 1.])

In [ ]:
t=torch.from_numpy(n)
t

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [ ]:
t.add_(1)

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)

In [ ]:
x = torch.empty(1)
print(x)

tensor([3.5873e-43])


In [ ]:
x.size()

torch.Size([1])

In [ ]:
x = torch.empty(2,3)
print(x)

tensor([[5.0137, 6.0000, 5.1486],
        [5.1581, 6.0000, 5.2128]])


In [ ]:
torch.empty(2,2,3)

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])

In [ ]:
y=x.view(6)
y

tensor([5.0137, 6.0000, 5.1486, 5.1581, 6.0000, 5.2128])

In [ ]:
z=x.view(1,-1)
z

tensor([[5.0137, 6.0000, 5.1486, 5.1581, 6.0000, 5.2128]])

In [ ]:
a= torch.ones(2,2)
b= torch.ones(2,2)
a,b

(tensor([[1., 1.],
         [1., 1.]]),
 tensor([[1., 1.],
         [1., 1.]]))

In [ ]:
a+b

tensor([[2., 2.],
        [2., 2.]])

In [ ]:
a-b

tensor([[0., 0.],
        [0., 0.]])

In [ ]:
a*b

tensor([[1., 1.],
        [1., 1.]])

In [ ]:
a/b

tensor([[1., 1.],
        [1., 1.]])

In [ ]:
a[1,1].item()

1.0

In [ ]:
torch.full((2,3),50)

tensor([[50, 50, 50],
        [50, 50, 50]])